In [1]:
# wap to find common element in a list

In [8]:
l1=[1,2,3,4,5,6,7,8]

l2=[10,20,4,40,7,90,100]


In [9]:
for i in l1: # For itrating in l1
    for j in l2: # fo ritrating in l2
        if i==j: # condition for common
            print("The common element is : ",i)
        elif i!=j: # condition for non common
            print(-1)


-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
The common element is :  4
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
The common element is :  7
-1
-1
-1
-1
-1
-1
-1
-1
-1


In [7]:
# by function


def com(l1,l2):
    for i in l1: # For itrating in l1
        for j in l2: # fo ritrating in l2
            if i==j: # condition for common
                print("The common element is : ",i)
            elif i!=j: # condition for non common
                print(-1)

com(l1,l2)

-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
The common element is :  7
-1
-1
-1
-1
-1
-1
-1
-1
-1


# numpy

In [13]:


import numpy as np



In [14]:
# wap to make array of 2 by 3

arr=np.array([[1,2,3],[4,5,6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [16]:
arr.shape

(2, 3)

In [17]:
arr.size

6

In [23]:
# predeined array


z=np.zeros(1)
print(z)

[0.]


In [26]:
np.zeros((10,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [38]:
np.zeros((10,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [42]:
# wap to make af 3d matrix of zeros

d3=np.zeros((1,3,3))

In [43]:
d3.shape

(1, 3, 3)

In [44]:
d3.ndim

3

In [45]:
d3

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [51]:
d=np.ones([5,2])

In [52]:
d

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [61]:
# wap to make a data of ones shape=5 by 6 wit the help of tuple



drr=np.zeros((5,6))

In [62]:
drr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [74]:
# arrange 

np.arange(100,0,-1)

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,
         9,   8,   7,   6,   5,   4,   3,   2,   1])

In [82]:
np.empty(10) # it has no fix value used for random generation

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [83]:
# wap to make 3 by 2 with empty

np.empty((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [87]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# transpose a matrix

In [89]:
# matrix 3*3

In [90]:
t=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [91]:
t

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [92]:
t.ndim

3

In [93]:
np.transpose(t)

array([[[1],
        [4],
        [7]],

       [[2],
        [5],
        [8]],

       [[3],
        [6],
        [9]]])

In [98]:
np.linspace(10,1)

array([10.        ,  9.81632653,  9.63265306,  9.44897959,  9.26530612,
        9.08163265,  8.89795918,  8.71428571,  8.53061224,  8.34693878,
        8.16326531,  7.97959184,  7.79591837,  7.6122449 ,  7.42857143,
        7.24489796,  7.06122449,  6.87755102,  6.69387755,  6.51020408,
        6.32653061,  6.14285714,  5.95918367,  5.7755102 ,  5.59183673,
        5.40816327,  5.2244898 ,  5.04081633,  4.85714286,  4.67346939,
        4.48979592,  4.30612245,  4.12244898,  3.93877551,  3.75510204,
        3.57142857,  3.3877551 ,  3.20408163,  3.02040816,  2.83673469,
        2.65306122,  2.46938776,  2.28571429,  2.10204082,  1.91836735,
        1.73469388,  1.55102041,  1.36734694,  1.18367347,  1.        ])

In [101]:
# ax=1
# ax=0

t

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [107]:

for i in t[0]:
    sum=0
    for j in i:
        sum+=j
    print(sum)
        

6
15
24


In [115]:
sum=0
for i in t[0]:
    j=0
    if j<3:
        sum+=i[j]
        print(sum)
    j=j+1
        

1
5
12


In [112]:
# axis=0 column

# axis=1 rows